version: '3.9'

services:
  fastapi:
    container_name: fastapi_container
    image: wotjr980321/ci_v1
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - 8080:8080
    volumes:
      - ~/workspace/_fastapi/ci_v1:/app
    restart: unless-stopped
    stdin_open: true
    tty: true
